# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 871)
        Dialog.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, "
                             "170, 255, 255), stop:1 rgba(255, 255, 255, 255))")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 450, 551, 401))
        self.listWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 380, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(190, 380, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.siteIndeed = QtWidgets.QRadioButton(Dialog)
        self.siteIndeed.setGeometry(QtCore.QRect(250, 310, 86, 17))
        self.siteIndeed.setObjectName("siteIndeed")
        self.siteLinkedin = QtWidgets.QRadioButton(Dialog)
        self.siteLinkedin.setGeometry(QtCore.QRect(340, 310, 86, 17))
        self.siteLinkedin.setObjectName("siteLinkedin")
        self.siteGlassdoor = QtWidgets.QRadioButton(Dialog)
        self.siteGlassdoor.setGeometry(QtCore.QRect(160, 310, 86, 17))
        self.siteGlassdoor.setObjectName("siteGlassdoor")
        self.siteGoogle = QtWidgets.QRadioButton(Dialog)
        self.siteGoogle.setGeometry(QtCore.QRect(430, 310, 86, 17))
        self.siteGoogle.setObjectName("siteGoogle")
        self.searchBox = QtWidgets.QTextEdit(Dialog)
        self.searchBox.setGeometry(QtCore.QRect(140, 100, 411, 31))
        self.searchBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.searchBox.setObjectName("searchBox")
        self.typeParttime = QtWidgets.QRadioButton(Dialog)
        self.typeParttime.setGeometry(QtCore.QRect(190, 210, 86, 17))
        self.typeParttime.setObjectName("typeParttime")
        self.typeFulltime = QtWidgets.QRadioButton(Dialog)
        self.typeFulltime.setGeometry(QtCore.QRect(280, 210, 86, 17))
        self.typeFulltime.setObjectName("typeFulltime")
        self.typeContract = QtWidgets.QRadioButton(Dialog)
        self.typeContract.setGeometry(QtCore.QRect(370, 210, 86, 17))
        self.typeContract.setObjectName("typeContract")
        self.verticalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBar.setGeometry(QtCore.QRect(590, 450, 20, 401))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 310, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 210, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 61, 20))
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(280, 260, 41, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(340, 260, 41, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 260, 81, 16))
        self.label_4.setObjectName("label_4")
        self.searchBox_2 = QtWidgets.QTextEdit(Dialog)
        self.searchBox_2.setGeometry(QtCore.QRect(140, 150, 411, 31))
        self.searchBox_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.searchBox_2.setObjectName("searchBox_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 150, 61, 20))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Search"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.siteIndeed.setText(_translate("Dialog", "Indeed"))
        self.siteLinkedin.setText(_translate("Dialog", "LinkedIn"))
        self.siteGlassdoor.setText(_translate("Dialog", "GlassDoor"))
        self.siteGoogle.setText(_translate("Dialog", "Google Jobs"))
        self.typeParttime.setText(_translate("Dialog", "Part-Time"))
        self.typeFulltime.setText(_translate("Dialog", "Full Time"))
        self.typeContract.setText(_translate("Dialog", "Contract"))
        self.label.setText(_translate("Dialog", "Job Site: "))
        self.label_2.setText(_translate("Dialog", "Type:"))
        self.label_3.setText(_translate("Dialog", "Search for:"))
        self.radioButton.setText(_translate("Dialog", "Yes"))
        self.radioButton_2.setText(_translate("Dialog", "No"))
        self.label_4.setText(_translate("Dialog", "Urgently Hiring:"))
        self.label_5.setText(_translate("Dialog", "Location:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
