# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JobSearch(object):
    def setupUi(self, JobSearch):
        JobSearch.setObjectName("JobSearch")
        JobSearch.resize(754, 800)
        JobSearch.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 255, 255), stop:1 rgba(170, 170, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(JobSearch)
        self.centralwidget.setObjectName("centralwidget")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(270, 210, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.searchBox_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.searchBox_2.setGeometry(QtCore.QRect(190, 80, 411, 31))
        self.searchBox_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.searchBox_2.setObjectName("searchBox_2")
        self.siteSimply = QtWidgets.QCheckBox(self.centralwidget)
        self.siteSimply.setGeometry(QtCore.QRect(450, 160, 86, 17))
        self.siteSimply.setObjectName("siteSimply")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 80, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 160, 51, 20))
        self.label.setObjectName("label")
        self.searchBox = QtWidgets.QTextEdit(self.centralwidget)
        self.searchBox.setGeometry(QtCore.QRect(190, 30, 411, 31))
        self.searchBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.searchBox.setObjectName("searchBox")
        self.siteLinkedin = QtWidgets.QCheckBox(self.centralwidget)
        self.siteLinkedin.setGeometry(QtCore.QRect(360, 160, 86, 17))
        self.siteLinkedin.setObjectName("siteLinkedin")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 61, 20))
        self.label_3.setObjectName("label_3")
        self.siteIndeed = QtWidgets.QCheckBox(self.centralwidget)
        self.siteIndeed.setGeometry(QtCore.QRect(270, 160, 86, 17))
        self.siteIndeed.setObjectName("siteIndeed")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 320, 651, 401))
        self.listWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.listWidget.setObjectName("listWidget")
        JobSearch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JobSearch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 21))
        self.menubar.setObjectName("menubar")
        JobSearch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JobSearch)
        self.statusbar.setObjectName("statusbar")
        JobSearch.setStatusBar(self.statusbar)

        self.retranslateUi(JobSearch)
        QtCore.QMetaObject.connectSlotsByName(JobSearch)

    def retranslateUi(self, JobSearch):
        _translate = QtCore.QCoreApplication.translate
        JobSearch.setWindowTitle(_translate("JobSearch", "MainWindow"))
        self.resetButton.setText(_translate("JobSearch", "Reset"))
        self.siteSimply.setText(_translate("JobSearch", "Simply Hired"))
        self.pushButton.setText(_translate("JobSearch", "Search"))
        self.label_5.setText(_translate("JobSearch", "Location:"))
        self.label.setText(_translate("JobSearch", "Job Site: "))
        self.siteLinkedin.setText(_translate("JobSearch", "LinkedIn"))
        self.label_3.setText(_translate("JobSearch", "Search for:"))
        self.siteIndeed.setText(_translate("JobSearch", "Indeed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JobSearch = QtWidgets.QMainWindow()
    ui = Ui_JobSearch()
    ui.setupUi(JobSearch)
    JobSearch.show()
    sys.exit(app.exec_())
